class All{
	public static void main(String[] args){
	Lollipop.unwrap();
	Lollipop.lick();
	Lollipop.bite();
	Lollipop.finish();
	Lollipop.disposeWrapper();
	MNCCompany.acquireCompany();
	MNCCompany.investInResearch();
	MNCCompany.manageFinances();
	MNCCompany.trainEmployees();
	MNCCompany.improveWorkCulture();
	 ICC.reviewMatch();
     ICC.handleSponsorships();
     ICC.promoteCricket();
     ICC.analyzePlayerStats();
     ICC.implementTechnology();
	 RCB.teamName();
     RCB.captain();
     RCB.headCoach();
     RCB.homeGround();
     RCB.bestPerformance();
	 IPLStats.getTopScorer();
     IPLStats.getTopWicketTaker();
     IPLStats.getTotalMatchesPlayed();
     IPLStats.getTotalWins();
     IPLStats.getTotalTitles();
	 Globe.rotateGlobe();
     Globe.showCountries();
     Globe.showLatitudeLongitude();
     Globe.zoomIn();
     Globe.zoomOut();
	}
	}